### ISSUE TITLE
Support for AWS Java SDK v2

### ISSUE THREAD

**Issue by janario** [aws/aws-secretsmanager-caching-java#5]
AWS Java SDK v2 was launched last year https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-x-released/

It would be nice to have this caching classes with the new API

**Comment by StevenEmelander** [comment]
Thank you for reaching out with this request.  The AWS Java SDK v2 was released in November and we have not yet investigated this.  Incorporating AWS Java SDK v2 will be considered for a future release.

**Comment by sullis** [comment]
see:  https://github.com/aws/aws-secretsmanager-caching-java/pull/6

**Comment by oridool** [comment]
see more recent SDK #13 with 2.15.19

**Comment by simonmarty** [comment]
We reviewed your request and in-order to prioritize it, we would like to understand your use-case to use SDKv2 over SDKv1. The two versions of the AWS SDK for Java can work together side-by-side without issue.

**Comment by oridool** [comment]
@simonmarty ,
The use case is running the application on EKS and utilizing 'IAM Role for Service Account' (IRSA).
Unfortunately, SDK 1.x couldn't support IRSA at the time this issue was created.
According to this [this](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html) , SDK 1.x added such support on Jan 2020. 
I didn't try it, since I'm already using SDK 2.x using a fork of this project.
Still, I believe it would be better to upgrade to v2.x because it is more advanced and many people already using it and now they are limited.
Or - if the library can somehow support both versions, it would be great.

**Comment by maciejwalkowiak** [comment]
@simonmarty they can work side by side but that's good as a temporary workaround not as a final solution. Why would I want to have 2 versions of the same library in my classpath?

**Comment by renatomariscal** [comment]
> we would like to understand your use-case to use SDKv2 over SDKv1.

This is unsatisfactory reason to dismiss this feature request. SDKv2 exists to replace v1. As such, tools like this one should be supporting, and promoting V2 usage. Not challenging its value like this answer.

**Comment by github-vincent-therry** [comment]
Hello,
We are using SSO to authenticate with AWS on our machines, and it requires (I think) to move to AWS SDK V2 using:
- software.amazon.awssdk.secretsmanager
- software.amazon.awssdk.sso (adding an SSOCredentialsProvider) that use our SSO profile seemlessly 
But in our case we are also using caching so we are stuck
